package frc.robot.Swerve.SwerveSubs;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.stzteam.forgemini.io.NetworkIO;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Swerve.SwerveConstants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.Vision.LimelightHelpers;


/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    private final Field2d field = new Field2d();

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    public final SysIdRoutineManager sysIdManager;

    public final String limelightName = "limelight";

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = null;

    private PathConstraints pathConstraints = new PathConstraints(
        4.5,
        4.0,
        Units.degreesToRadians(540),
        Units.degreesToRadians(720)
    );

    private final PoseFinder finder;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants,SwerveModuleConstants<?, ?, ?>... modules) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        this.sysIdManager = new SysIdRoutineManager(this);
        this.m_sysIdRoutineToApply = sysIdManager.m_sysIdRoutineTranslation;

        configurePathPlanner();
        SmartDashboard.putData("Field", field);

        this.finder = new PoseFinder(this, pathConstraints);

    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants,double odometryUpdateFrequency,SwerveModuleConstants<?, ?, ?>... modules) {
        
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        this.sysIdManager = new SysIdRoutineManager(this);
        this.m_sysIdRoutineToApply = sysIdManager.m_sysIdRoutineTranslation;

        configurePathPlanner();

        this.finder = new PoseFinder(this, pathConstraints);
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }

        this.sysIdManager = new SysIdRoutineManager(this);
        this.m_sysIdRoutineToApply = sysIdManager.m_sysIdRoutineTranslation;

        configurePathPlanner();

        this.finder = new PoseFinder(this, pathConstraints);
    }

    public void setSysIdRoutine(SysIdRoutine routine){
        this.m_sysIdRoutineToApply = routine;
    }

    private void configurePathPlanner() {
        try {
            // Cargar configuración de la GUI de PathPlanner (RobotConfig)
            RobotConfig config = RobotConfig.fromGUISettings();

            AutoBuilder.configure(
                () -> this.getState().Pose,      // 1. Supplier de Pose
                this::resetPose,         // 2. Consumer para resetear pose
                this::getChassisSpeeds, // 3. Supplier de Velocidades actuales
                (speeds, feedforwards) -> this.setControl(SwerveRequestFactory.pathPlannerRequest.withSpeeds(speeds)), 
                // -----------------------------

                new PPHolonomicDriveController(
                    new PIDConstants(5.0, 0.0, 0.0), // PID de Traslación
                    new PIDConstants(5.0, 0.0, 0.0)  // PID de Rotación
                ),
                config,
                () -> {
                    var alliance = DriverStation.getAlliance();
                    return alliance.isPresent() && alliance.get() == DriverStation.Alliance.Red;
                },
                this
            );
        } catch (Exception e) {
            DriverStation.reportError("Fallo al configurar PathPlanner: " + e.getMessage(), true);
        }
    }

    public ChassisSpeeds getChassisSpeeds() {
        return getKinematics().toChassisSpeeds(getState().ModuleStates);
    }
    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {

        if (m_sysIdRoutineToApply == null){ return Commands.none();}

        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {

        if (m_sysIdRoutineToApply == null){ return Commands.none();}

        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
        
        updateVision();
        field.setRobotPose(getState().Pose);

        NetworkIO.set("Swerve", "Pose", getState().Pose);
        
    }

    private void updateVision() {
        LimelightHelpers.SetRobotOrientation(limelightName, this.getPigeon2().getRotation2d().getDegrees(), 0, 0, 0, 0, 0);
        LimelightHelpers.PoseEstimate mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(limelightName);

        if (mt2 == null || mt2.tagCount == 0) return;

        if (Math.abs(this.getPigeon2().getAngularVelocityZWorld().getValueAsDouble()) > 720) return;
        
        addVisionMeasurement(mt2.pose, mt2.timestampSeconds, VecBuilder.fill(.7,.7,9999999));
    }

    public void aproachY() { 
            double ty = LimelightHelpers.getTY(limelightName);
            double xSpeed = -0.1 * ty;

        setControl(SwerveRequestFactory.simpleDriveRequest
                .withVelocityX(xSpeed)
                .withVelocityY(0)
                .withRotationalRate(0)
    );}

    /**
     * MODO 1: AUTO-DOCK (El robot hace todo)
     * Se acerca al tag y se alinea usando RobotCentric.
     */
    public void aproachXY() { 
        // 1. Obtener datos de Limelight
        double ty = LimelightHelpers.getTY(limelightName); // Distancia vertical
        double tx = LimelightHelpers.getTX(limelightName); // Error horizontal
        boolean hasTarget = LimelightHelpers.getTV(limelightName);

        if (!hasTarget) {
            // Si no ve nada, frenar por seguridad
            setControl(SwerveRequestFactory.idle);
            return;
        }

        // 2. Calcular velocidades (PID Proporcional simple)
        // ty positivo = target arriba (lejos) -> ir adelante (+X)
        // tx positivo = target a la derecha -> girar a la derecha (-Rot)
        
        double forwardSpeed = ty * 0.1;  // KP Distance
        double turnSpeed    = tx * -0.05; // KP Rotation (Invertido)
        double strafeSpeed  = tx * 0.05; // KP Strafe (Opcional: moverse lateralmente para centrar)

        // 3. Aplicar control ROBOT CENTRIC desde tu Factory
        setControl(SwerveRequestFactory.driveRobotCentric
            .withVelocityX(forwardSpeed)
            .withVelocityY(0) // O usa strafeSpeed si quieres centrado perfecto
            .withRotationalRate(turnSpeed)
        );
    }

    /**
     * MODO 2: AIM ASSIST (Para Teleop)
     * El piloto controla X/Y, el robot controla el giro hacia el tag.
     * @param xSpeed Velocidad X del Joystick
     * @param ySpeed Velocidad Y del Joystick
     */
    public void driveFacingTag(double xSpeed, double ySpeed) {
        double tx = LimelightHelpers.getTX("limelight");
        boolean hasTarget = LimelightHelpers.getTV("limelight");

        // Calcular el ángulo actual del robot
        Rotation2d currentHeading = this.getPigeon2().getRotation2d();

        // Si vemos tag, el ángulo deseado es: (MiAngulo - ErrorDelTag)
        // Si no vemos tag, mantenemos el ángulo actual
        Rotation2d targetHeading = hasTarget 
            ? currentHeading.minus(Rotation2d.fromDegrees(tx)) 
            : currentHeading;

        // Usamos el request de Aim de la Factory
        setControl(SwerveRequestFactory.aimRequest
            .withVelocityX(xSpeed)
            .withVelocityY(ySpeed)
            .withTargetDirection(targetHeading)
        );
    }
    
    public void moveX(double speed) { 
        setControl(SwerveRequestFactory.simpleDriveRequest.withVelocityX(speed));
    }

    public void moveY(double speed) { 
        setControl(SwerveRequestFactory.simpleDriveRequest.withVelocityY(speed));
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public PoseFinder getPoseFinder(){
        return finder;
    }

}